### ISSUE TITLE
KafkaUtils create direct stream throws exception in Spark driver

### ISSUE THREAD

**Issue by yxian29** [samsonxian/Trajectory-Companion-Finder#2]
I'm having issues while trying to create direct stream to read from kafka

```
SparkConf sparkConf = new SparkConf().SetAppName("blabla");
JavaStreamingContext ssc = new JavaStreamingContext(sparkConf, Durations.seconds(1));
Set<String> topics = new HashSet():
topics.add("myTopic");
Map<String, String> kafkaParams = new HashMap();
kafkaParams.put("metadata.broker.list", "localhost:9092");

JavaPairInputDStream<String, String> inputDStream = KafkaUtils.createDirectStream(
ssc, String.class, String.class, StringDecoder.class, StringDecoder.class,
kafkaParams, topics);
```

The current Spark version is 1.5.1. I have started zookeeper at port 2181 and kafka server 0.9.0.1 at port 9092. But I get the following error in the Spark driver:

```
Exception in thread "main" java.lang.ClassCastException: kafka.cluster.BrokerEndPoint cannot be cast to kafka.cluster.Broker
at org.apache.spark.streaming.kafka.KafkaCluster$$anonfun$2$$anonfun$3$$anonfun$apply$6$$anonfun$apply$7.apply(KafkaCluster.scala:90)
at scala.Option.map(Option.scala:145)
at org.apache.spark.streaming.kafka.KafkaCluster$$anonfun$2$$anonfun$3$$anonfun$apply$6.apply(KafkaCluster.scala:90)
at org.apache.spark.streaming.kafka.KafkaCluster$$anonfun$2$$anonfun$3$$anonfun$apply$6.apply(KafkaCluster.scala:87)
```

**Comment by samsonxian** [comment]
Just to keep a note to myself. This is due to Spark streaming and Kafka version compatibility.
```
Kafka: Spark Streaming 1.5.2 is compatible with Kafka 0.8.2.1
```
